-- MySQL Script generated by MySQL Workbench
-- 02/28/18 16:23:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EnergySom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EnergySom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EnergySom` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `EnergySom` ;

-- -----------------------------------------------------
-- Table `EnergySom`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`Marca` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergySom`.`Modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`Modelo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdMarca` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Modelo_Marca_idx` (`IdMarca` ASC),
  CONSTRAINT `fk_Modelo_Marca`
    FOREIGN KEY (`IdMarca`)
    REFERENCES `EnergySom`.`Marca` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergySom`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`Categoria` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergySom`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`Produto` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdCategoria` INT NOT NULL,
  `IdMarca` INT NOT NULL,
  `IdModelo` INT NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `ValorCusto` FLOAT NULL,
  `ValorMax` FLOAT NULL,
  `ValorMini` FLOAT NULL,
  `Codigo` VARCHAR(45) NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Produto_Modelo1_idx` (`IdModelo` ASC),
  INDEX `fk_Produto_Marca1_idx` (`IdMarca` ASC),
  INDEX `fk_Produto_Categoria1_idx` (`IdCategoria` ASC),
  CONSTRAINT `fk_Produto_Modelo1`
    FOREIGN KEY (`IdModelo`)
    REFERENCES `EnergySom`.`Modelo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Marca1`
    FOREIGN KEY (`IdMarca`)
    REFERENCES `EnergySom`.`Marca` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Categoria1`
    FOREIGN KEY (`IdCategoria`)
    REFERENCES `EnergySom`.`Categoria` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergySom`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`Cliente` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `Cpf` VARCHAR(20) NULL,
  `Rg` VARCHAR(20) NULL,
  `Rua` VARCHAR(50) NULL,
  `Numero` VARCHAR(10) NULL,
  `Bairro` VARCHAR(40) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Telefone` VARCHAR(20) NULL,
  `Celular1` VARCHAR(20) NULL,
  `Celular2` VARCHAR(20) NULL,
  `Nascimento` DATE NULL,
  `Observacao` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergySom`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`Funcionario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Cpf` VARCHAR(20) NULL,
  `Rg` VARCHAR(20) NULL,
  `Nascimento` DATE NULL,
  `Telefone` VARCHAR(20) NULL,
  `Celular1` VARCHAR(20) NULL,
  `Celular2` VARCHAR(20) NULL,
  `Login` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergySom`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`Venda` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdCliente` INT NOT NULL,
  `IdFuncionario` INT NOT NULL,
  `Data` DATE NULL,
  `TotalVenda` FLOAT NULL,
  `FormaPagamento` VARCHAR(20) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Venda_Cliente1_idx` (`IdCliente` ASC),
  INDEX `fk_Venda_Funcionario1_idx` (`IdFuncionario` ASC),
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `EnergySom`.`Cliente` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Funcionario1`
    FOREIGN KEY (`IdFuncionario`)
    REFERENCES `EnergySom`.`Funcionario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergySom`.`VendaML`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`VendaML` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdFuncionario` INT NOT NULL,
  `IdProduto` INT NOT NULL,
  `TotalVenda` FLOAT NULL,
  `Data` DATE NULL,
  `Horario` VARCHAR(10) NULL,
  `Rastreio` VARCHAR(20) NULL,
  `Detalhes` VARCHAR(60) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_VendaML_Produto1_idx` (`IdProduto` ASC),
  INDEX `fk_VendaML_Funcionario1_idx` (`IdFuncionario` ASC),
  CONSTRAINT `fk_VendaML_Produto1`
    FOREIGN KEY (`IdProduto`)
    REFERENCES `EnergySom`.`Produto` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VendaML_Funcionario1`
    FOREIGN KEY (`IdFuncionario`)
    REFERENCES `EnergySom`.`Funcionario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergySom`.`SituacaoEmpresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`SituacaoEmpresa` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Lucros` VARCHAR(45) NULL,
  `Despesas` VARCHAR(45) NULL,
  `Data` VARCHAR(10) NULL,
  `LucroBoll` TINYINT(1) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergySom`.`ItemVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`ItemVenda` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdVenda` INT NOT NULL,
  `IdProduto` INT NOT NULL,
  `Quantidade` FLOAT NULL,
  `Preco` FLOAT NULL,
  `Total` FLOAT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Produto_has_Venda_Venda1_idx` (`IdVenda` ASC),
  INDEX `fk_Produto_has_Venda_Produto1_idx` (`IdProduto` ASC),
  CONSTRAINT `fk_Produto_has_Venda_Produto1`
    FOREIGN KEY (`IdProduto`)
    REFERENCES `EnergySom`.`Produto` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Venda_Venda1`
    FOREIGN KEY (`IdVenda`)
    REFERENCES `EnergySom`.`Venda` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergySom`.`ItemVendaML`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`ItemVendaML` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdVenda` INT NOT NULL,
  `IdProduto` INT NOT NULL,
  INDEX `fk_Produto_has_VendaML_VendaML1_idx` (`IdVenda` ASC),
  INDEX `fk_Produto_has_VendaML_Produto1_idx` (`IdProduto` ASC),
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_Produto_has_VendaML_Produto1`
    FOREIGN KEY (`IdProduto`)
    REFERENCES `EnergySom`.`Produto` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_VendaML_VendaML1`
    FOREIGN KEY (`IdVenda`)
    REFERENCES `EnergySom`.`VendaML` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergySom`.`Valida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`Valida` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Mes` INT NULL,
  `Ano` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergySom`.`Despesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnergySom`.`Despesas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(150) NULL,
  `Valor` FLOAT NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `funcionario` (`Id`, `Nome`, `Cpf`, `Rg`, `Nascimento`, `Telefone`, `Celular1`, `Celular2`, `Login`, `Senha`) VALUES
(1, 'ROOT', NULL, NULL, NULL, NULL, NULL, NULL, 'login', '123'),
(2, 'root', NULL, NULL, '2018-02-14', NULL, NULL, NULL, 'login', '123');

INSERT INTO `valida` (`Id`, `Mes`, `Ano`) VALUES
(1, 3, 2018);