/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Danilo-NOTE
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(MAXIMIZED_BOTH);
        //Venda.setEnabled(false);
        Consulta.setEnabled(false);
        MarcLivre.setEnabled(false);
        Relatorios.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Venda = new javax.swing.JLabel();
        Consulta = new javax.swing.JLabel();
        Cliente = new javax.swing.JLabel();
        MarcLivre = new javax.swing.JLabel();
        Relatorios = new javax.swing.JLabel();
        Estoque = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Venda.setBackground(new java.awt.Color(204, 0, 255));
        Venda.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Venda.setForeground(new java.awt.Color(227, 227, 227));
        Venda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Venda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Cashier.png"))); // NOI18N
        Venda.setText("Venda");
        Venda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Venda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VendaMouseClicked(evt);
            }
        });

        Consulta.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Consulta.setForeground(new java.awt.Color(227, 227, 227));
        Consulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Analytics.png"))); // NOI18N
        Consulta.setText("Consulta");
        Consulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Consulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaMouseClicked(evt);
            }
        });

        Cliente.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Cliente.setForeground(new java.awt.Color(227, 227, 227));
        Cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Chat.png"))); // NOI18N
        Cliente.setText("Cliente");
        Cliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClienteMouseClicked(evt);
            }
        });

        MarcLivre.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        MarcLivre.setForeground(new java.awt.Color(227, 227, 227));
        MarcLivre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MarcLivre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Laptop.png"))); // NOI18N
        MarcLivre.setText("<html><p align = \"center\">Mercado <br> Livre</p></html> "); // NOI18N
        MarcLivre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MarcLivre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MarcLivre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarcLivreMouseClicked(evt);
            }
        });

        Relatorios.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Relatorios.setForeground(new java.awt.Color(227, 227, 227));
        Relatorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Graph.png"))); // NOI18N
        Relatorios.setText("Relatórios");
        Relatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Relatorios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Relatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RelatoriosMouseClicked(evt);
            }
        });

        Estoque.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Estoque.setForeground(new java.awt.Color(227, 227, 227));
        Estoque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Conveyor.png"))); // NOI18N
        Estoque.setText("Estoque");
        Estoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Estoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Estoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstoqueMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(227, 227, 227));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Boss.png"))); // NOI18N
        jLabel8.setText("Vendedores");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(Estoque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Venda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Consulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MarcLivre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
            .addComponent(Relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(Venda)
                .addGap(0, 0, 0)
                .addComponent(Consulta)
                .addGap(0, 0, 0)
                .addComponent(MarcLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Relatorios))
        );

        pnlPrincipal.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1111, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClienteMouseClicked
        ClienteView Cliente = new ClienteView();
            pnlPrincipal.removeAll();
            pnlPrincipal.add(Cliente);
            pnlPrincipal.updateUI();
    }//GEN-LAST:event_ClienteMouseClicked

    private void VendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VendaMouseClicked
        VendaView venda = new VendaView();
            pnlPrincipal.removeAll();
            pnlPrincipal.add(venda);
            pnlPrincipal.updateUI();
    }//GEN-LAST:event_VendaMouseClicked

    private void EstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstoqueMouseClicked
        ProdutoView Produto = new ProdutoView();
            pnlPrincipal.removeAll();
            pnlPrincipal.add(Produto);
            pnlPrincipal.updateUI();
    }//GEN-LAST:event_EstoqueMouseClicked

    private void ConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaMouseClicked

    private void MarcLivreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcLivreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcLivreMouseClicked

    private void RelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelatoriosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatoriosMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        FuncionarioView Funcionario = new FuncionarioView();
            pnlPrincipal.removeAll();
            pnlPrincipal.add(Funcionario);
            pnlPrincipal.updateUI();
    }//GEN-LAST:event_jLabel8MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cliente;
    private javax.swing.JLabel Consulta;
    private javax.swing.JLabel Estoque;
    private javax.swing.JLabel MarcLivre;
    private javax.swing.JLabel Relatorios;
    private javax.swing.JLabel Venda;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
